name: My first gihub action
on: [push]
jobs:
    print-hello-world:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello world"
            - run: echo "This is step 2"
    print-hello-world2:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello world"
            - run: echo "This is step 2"